### PR TITLE
Support privileged user creation/deletion

### PR DESCRIPTION
**Pull request by dav3r**
Add a command-line variable to enable creation of users that are allowed to `sudo`.

### CODE REVIEW

**Review by mcdonnnj — APPROVED** [review]
LGTM ✔

**Review by felddy — APPROVED** [review]
Nifty.  approved = "True"|bool

**Review by jsf9k — APPROVED** [review]
I would have created a group with passwordless sudo, then added/removed the users from that group as desired.  This works too, although it makes the sudoers file more verbose.

**Comment by dav3r** [comment]
@jsf9k I went ahead and implemented it the way you suggested - thanks for the feedback!

**Pull request merged**
